name: color_puzzle_relax_game
description: A minimalist gradient puzzle relaxation game.
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  audioplayers: ^5.2.1
  meta: ^1.11.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
